site_name: IL-Datasets
theme: readthedocs
nav:
  - Home: 'index.md'
  - About:
    - 'License': 'about/license.md'
    - 'Release Notes': 'about/release-notes.md'
  - Tutorials:
    - 'Installation': 'tutorials/install.md'
    - 'Creating a new dataset': 'tutorials/creation.md'
    - 'Using available datasets': 'tutorials/datasets.md'
    - 'Benchmarking': 'tutorials/benchmark.md'
  - Algorithms:
    - 'Default Method Class': 'algorithms/method.md'
    - 'Behavioural Cloning': 'algorithms/bc.md'
    - 'Behavioural Cloning from Observation': 'algorithms/bco.md'
