Default:
  lr: 5e-4
  idm_lr: 5e-4
  idm: 'MlpWithAttention'
  policy: 'MlpWithAttention'
  random_episodes: 10000

CartPole-v1:
  lr: 5e-4
  idm_lr: 5e-4
  idm: 'MlpWithAttention'
  policy: 'MlpWithAttention'
  random_episodes: 50

MountainCar-v0:
  lr: 1e-3
  idm_lr: 1e-3
  idm: 'MlpWithAttention'
  policy: 'MlpWithAttention'
  random_episodes: 100

Acrobot-v1:
  lr: 1e-3
  idm_lr: 1e-3
  idm: 'MlpWithAttention'
  policy: 'MlpWithAttention'
  random_episodes: 100

LunarLander-v2:
  lr: 5e-4
  idm_lr: 5e-4
  idm: 'MlpWithAttention'
  policy: 'MlpWithAttention'
  random_episodes: 100
