Default:
  lr: 5e-4
  policy: 'MlpPolicy'

CartPole:
  lr: 6e-4 
  policy: 'MlpPolicy'

MountainCar:
  lr: 1.3e-3
  policy: 'MlpPolicy'

Acrobot:
  lr: 1.6e-3 
  policy: 'MlpPolicy'

Maze:
  lr: 5e-4
  policy: 'CnnPolicy'
